### ISSUE TITLE
Change decimal length

### ISSUE THREAD

**Issue by fadhly-permata** [benhurott/flutter-masked-text#19]
Hi,

First, I want to say thanks for making this extension.

AFAIK, your `MoneyMaskedTextController` only supports 2 digits decimal length. Is there any way to change the fraction digits length?

for example:
`1,234,567.789` or `1,234,567.7890` or `1,234,567.78901` or even without decimals like `1,234,567`

Thank you,

---
P.S: Sorry for my bad English

**Comment by fadhly-permata** [comment]
After doing a small investigation, I found the solution on line 200 (on version 0.7.0) :

`
String textRepresentation =
        value.toStringAsFixed(2).replaceAll('.', this.decimalSeparator);
`

IDK if adding the decimal length feature will take a big efforts or not. But, may you add this value into constructor so I can change the decimal length programatically.

**Comment by fadhly-permata** [comment]
Maybe my package can help you with this feature:

[flutter_money_formatter](https://pub.dartlang.org/packages/flutter_money_formatter)

**Comment by fadhly-permata** [comment]
Because there is no response, I will close this discussion. And I thought of making my own components that could meet my needs.

thank you

**Comment by bhrott** [comment]
Hi bro!

Sorry for the late response, it required a little refactoring because I coded that part in a bad way =/.

But I released a version `0.8.0` with your requirements.
If you can, please, test and give some feedback =).

Here is the [DOCS](https://github.com/benhurott/flutter-masked-text#defining-decimal-places-v080)!

See you o/
